### PR TITLE
feat(dashboard): enable selection of score names in legend of chart + slider

### PR DESCRIPTION
**Pull request by khareyash05**
## What does this PR do?

Enable selecting score when clicking on the items in legend and legend slider

Fixes #853 

https://www.loom.com/share/75662e6f970f4e5ebada0cbfa2a11167?sid=b10db667-5cdb-43a8-a9ae-5658944b3dee

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (does not change functionality, e.g. code style improvements, linting)
- [ ] This change requires a documentation update

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Comment by lkNGAT** [comment]
Hi @khareyash05 
That looks really nice 👏

Just one question:
It seems like the "alpha"  score does not get unselected?

**Comment by khareyash05** [comment]
> Hi @khareyash05 
> That looks really nice 👏
> 
> Just one question:
> It seems like the "alpha"  score does not get unselected? 
> 
> 

It does lemme shoot another video.

**Comment by khareyash05** [comment]
> Hi @khareyash05 That looks really nice 👏
> 
> Just one question: It seems like the "alpha" score does not get unselected?
https://www.loom.com/share/c7928d3e4c92499f9e141ec7a476a53a?sid=1cd31088-19db-4efe-b348-c8509927f0dd . Please Have a look at this and let me know if any further changes are required

**Comment by lkNGAT** [comment]
@khareyash05 
Looks great.
Thanks a lot :)

**Comment by khareyash05** [comment]
Thank you. Will have to wait for it to be merged before you can use it.😄

**Review by marcklingen — APPROVED** [review]
thanks!

**Pull request merged**
