### PR TITLE
Feat/add keycloak

### PR DESCRIPTION
**Pull request by abartrimcmgx**
This pull request introduces changes primarily to the authentication system of the web application, with a focus on adding support for Keycloak.

Keycloak support:

* [`web/src/env.mjs`](diffhunk://#diff-2f0c198838dc2284f6c49d813934f356195aca6d17f3be3948402a4422ba538cR70-R73): The environment variables for Keycloak have been added, including the client ID, client secret, issuer, and a boolean for account linking. [[1]](diffhunk://#diff-2f0c198838dc2284f6c49d813934f356195aca6d17f3be3948402a4422ba538cR70-R73) [[2]](diffhunk://#diff-2f0c198838dc2284f6c49d813934f356195aca6d17f3be3948402a4422ba538cR178-R182)
* [`web/src/pages/auth/sign-in.tsx`](diffhunk://#diff-4b54b8e565677da17095f4f4031037c2d692fec31c2a09d34e02dc226601ba9dR51): Keycloak has been added as an authentication provider. This includes changes to the `PageProps` type, the `getServerSideProps` function, and the `SSOButtons` function. [[1]](diffhunk://#diff-4b54b8e565677da17095f4f4031037c2d692fec31c2a09d34e02dc226601ba9dR51) [[2]](diffhunk://#diff-4b54b8e565677da17095f4f4031037c2d692fec31c2a09d34e02dc226601ba9dR81-R84) [[3]](diffhunk://#diff-4b54b8e565677da17095f4f4031037c2d692fec31c2a09d34e02dc226601ba9dR158-R171)
* [`web/src/server/auth.ts`](diffhunk://#diff-e58e5990c970014f04ffaa1ab621f49c03a311caff05ded1408ecfb18f5208ebL187-R212): The Keycloak provider has been added to the static providers array. An additional hack has been implemented to remove certain properties from the account object to prevent Prisma from throwing an error. [[1]](diffhunk://#diff-e58e5990c970014f04ffaa1ab621f49c03a311caff05ded1408ecfb18f5208ebL187-R212) [[2]](diffhunk://#diff-e58e5990c970014f04ffaa1ab621f49c03a311caff05ded1408ecfb18f5208ebR1-R31)

Code organization:

* `web/src/env.mjs`, `web/src/pages/auth/sign-in.tsx`, `web/src/server/auth.ts`: The import statements have been reordered. [[1]](diffhunk://#diff-2f0c198838dc2284f6c49d813934f356195aca6d17f3be3948402a4422ba538cL1-R2) [[2]](diffhunk://#diff-4b54b8e565677da17095f4f4031037c2d692fec31c2a09d34e02dc226601ba9dL1) [[3]](diffhunk://#diff-e58e5990c970014f04ffaa1ab621f49c03a311caff05ded1408ecfb18f5208ebR1-R31)

### CODE REVIEW

**Comment by abartrimcmgx** [comment]
Put this up before it was ready...

**Comment by marcklingen** [comment]
no worries, let me know once I should have a look!

**Comment by hegeduscs** [comment]
I would like to use keycloak .. so how is this work going on?

**Comment by marcklingen** [comment]
Still open for contributions on this, should be easy to add

**Pull request closed without merging**
