### PR TITLE
feat(auth): add `AUTH_IGNORE_ACCOUNT_FIELDS` to sanitize IDP fields before creating an account

### PR DESCRIPTION
**Pull request by tovarisch-ildar**
## What does this PR do?

This PR adds field sanitization before creating an Account in the authentication process. This change is necessary because passing extraneous fields can cause sign-in via SSO to fail. Similar issues have been discussed and addressed in [this discussion](https://github.com/orgs/langfuse/discussions/2165)

## Type of change

- [ ] Bug fix for https://github.com/langfuse/langfuse/issues/4705

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes (there are some problems with running tests in GitHub Codespaces, even on the **main** branch)

----

> [!IMPORTANT]
> Sanitizes fields in `linkAccount` function to prevent SSO sign-in failures by removing extraneous fields not in the `Account` model.
> 
>   - **Behavior**:
>     - Sanitize fields in `linkAccount` function in `auth.ts` to remove extraneous fields not present in the `Account` model.
>     - Prevents SSO sign-in failures due to incompatible data fields.
>   - **Adapters**:
>     - Extend `PrismaAdapter` in `auth.ts` to include field sanitization logic for `Account` model.
>   - **Misc**:
>     - Add `Prisma` import in `auth.ts` for accessing data model information.
> 
> <sup>This description was created by </sup>[Ellipsis](https://www.ellipsis.dev?ref=langfuse%2Flangfuse&utm_source=github&utm_medium=referral)<sup> for e4d2c2b85a2f60b0094730c1d5b8dc2cbce76af8. It will automatically update as commits are pushed.</sup>

### CODE REVIEW

**Comment by marcklingen** [comment]
I was just starting to work on this, thanks for the contribution. Can you accept the CLA? Have you tested whether this resolves your issue?

**Comment by tovarisch-ildar** [comment]
> I was just starting to work on this, thanks for the contribution. Can you accept the CLA? Have you tested whether this resolves your issue?

Yes, of course, I've accepted the CLA. I tested it in my infrastructure, and it works perfectly. However, the tests are failing (even in GitHub Codespaces on main branch), but I assume my changes shouldn't have broken anything

**Comment by marcklingen** [comment]
Please see comment above regarding the CLA, apparently your local git config uses an email that is not part of your github profile

**Comment by tovarisch-ildar** [comment]
> > Prisma.dmmf is an internal api and use is discouraged. I'd change this to an allowlist of available keys. I do not expect this to change often, thus, this should be maintainable with a comment in the prisma schema
> 
> I have the changes for this already locally, will push to this branch

Yeah, ok. Thanks

**Comment by marcklingen** [comment]
Unfortunately, this break google auth for me when testing this locally.
```
Argument `user` is missing.
```

Implementation
```
// Extend Prisma Adapter
const prismaAdapter = PrismaAdapter(prisma);
const ALLOWED_ACCOUNT_FIELDS = [
  "id",
  "user_id",
  "type",
  "provider",
  "providerAccountId",
  "refresh_token",
  "access_token",
  "expires_at",
  "expires_in",
  "ext_expires_in",
  "token_type",
  "scope",
  "id_token",
  "session_state",
  "refresh_token_expires_in",
  "created_at",
  "user",
];
const extendedPrismaAdapter: Adapter = {
  ...prismaAdapter,
  async createUser(profile: Omit<AdapterUser, "id">) {
    if (!prismaAdapter.createUser)
      throw new Error("createUser not implemented");
    if (
      env.NEXT_PUBLIC_SIGN_UP_DISABLED === "true" ||
      env.AUTH_DISABLE_SIGNUP === "true"
    ) {
      throw new Error("Sign up is disabled.");
    }
    if (!profile.email) {
      throw new Error(
        "Cannot create db user as login profile does not contain an email: " +
          JSON.stringify(profile),
      );
    }

    const user = await prismaAdapter.createUser(profile);

    await createProjectMembershipsOnSignup(user);

    return user;
  },

  async linkAccount(data: AdapterAccount) {
    if (!prismaAdapter.linkAccount)
      throw new Error("NextAuth: prismaAdapter.linkAccount not implemented");

    // Some sso provider's return incompatible data with the nextjs-auth schema
    // (refresh_expires_in, not-before-policy in, resource).
    // So, we need to remove this data from the payload before linking an account.
    // https://github.com/langfuse/langfuse/issues/4705
    // https://github.com/nextauthjs/next-auth/issues/7655
    for (const key in data) {
      if (!ALLOWED_ACCOUNT_FIELDS.includes(key)) {
        logger.debug(
          `[Auth] Removing incompatible key from account data: ${key}`,
        );
        delete data[key];
      }
    }

    await prismaAdapter.linkAccount(data);
  },
};
```

Do you have an idea how to best fix this?

**Comment by tovarisch-ildar** [comment]
Maybe just add a separate environment variable with a list of fields to delete? This approach will not break anything, and developers can manage it on their side as they wish and there will be no need to update the `ALLOWED_ACCOUNT_FIELDS` array in case of future schema updates

**Comment by marcklingen** [comment]
> Maybe just add a separate environment variable with a list of fields to delete? This approach will not break anything, and developers can manage it on their side as they wish and there will be no need to update the `ALLOWED_ACCOUNT_FIELDS` array in case of future schema updates

Good idea. I suggest keeping the existing logic implemented for Keycloak and adding an optional loop over comma-separated keys that are removed from the account fields. I'd probably recommend making this a disallow list to prevent accidental removal of fields as in the google example that I encountered on localhost. During setup of a new self-hosted langfuse instance, one can then incrementally add to this array until there are no error logs left when trying to authenticate.

**Comment by tovarisch-ildar** [comment]
> > Maybe just add a separate environment variable with a list of fields to delete? This approach will not break anything, and developers can manage it on their side as they wish and there will be no need to update the `ALLOWED_ACCOUNT_FIELDS` array in case of future schema updates
> 
> Good idea. I suggest keeping the existing logic implemented for Keycloak and adding an optional loop over comma-separated keys that are removed from the account fields. I'd probably recommend making this a disallow list (e.g. `AUTH_IGNORE_ACCOUNT_FIELDS=organization,level`) to prevent accidental removal of fields as in the google example that I encountered on localhost. During setup of a new self-hosted langfuse instance, one can then incrementally add to this array until there are no error logs left when trying to authenticate.
> 
> Do you think comma-separated is good enough or does it need to be a stringified json array to make sure escapes work correctly for custom args? No strong opinion here.

I think a comma-separated array should be sufficient, as a similar array is used in [AUTH_DOMAINS_WITH_SSO_ENFORCEMENT](https://github.com/tovarisch-ildar/langfuse/blob/main/web/src/features/auth-credentials/server/signupApiHandler.ts#L45)

**Comment by tovarisch-ildar** [comment]
@marcklingen 
I made the changes but couldn't test them locally because the Docker image is built for version 3 and requires clickhouse. If the PR is merged, will these changes be available in version 2? We are currently unable to run version 3 in our infrastructure

**Comment by tovarisch-ildar** [comment]
> > I made the changes but couldn't test them locally because the Docker image is built for version 3 and requires clickhouse. If the PR is merged, will these changes be available in version 2? We are currently unable to run version 3 in our infrastructure
> 
> Once merged, we can cherry-pick these changes for v2. Can you create an issue with details on what blocks the v3 deployment on your end? Would love to help.

It seems that version 2 will suffice for us at the moment, and we are unable to use ClickHouse right now due to internal issues. :-)

**Comment by marcklingen** [comment]
> we are unable to use ClickHouse right now due to internal issues

Can you share more details? Would love to help resolve this as we have worked with many teams who run Langfuse self-hosted

**Comment by marcklingen** [comment]
release here on v2 branch: https://github.com/langfuse/langfuse/releases/tag/v2.93.7

**Comment by tovarisch-ildar** [comment]
Thank you very much! Alright, I'll get back to you with questions about the version 3 a bit later. Thanks again! :-)

**Pull request merged**
