### PR TITLE
fix(docker): remove the need for runtime variables at build time

### LINKED ISSUE #1015: feat(docker): skip validation of environment variables/secrets at docker build time
See discussion here https://github.com/orgs/langfuse/discussions/1013

Proposed changes
- [ ] skip validation of environment secrets as suggested here https://github.com/t3-oss/t3-env/issues/85 in [/src/env.mjs](https://github.com/langfuse/langfuse/blob/main/src/env.mjs)
- [ ] remove secrets from CI in (both build and test): [pipeline.yml](https://github.com/langfuse/langfuse/blob/main/.github/workflows/pipeline.yml)
- [ ] remove secrets from [docker-compose.build.yml](https://github.com/langfuse/langfuse/blob/main/docker-compose.build.yml)
- [ ] Test locally that runtime errors still work after the change

### PR DESCRIPTION
**Pull request by khareyash05**
## What does this PR do?

Fixes #1015 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Chore (refactoring code, technical debt, workflow improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (does not change functionality, e.g. code style improvements, linting)
- [ ] This change requires a documentation update

## Mandatory Tasks

- [X] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Comment by marcklingen** [comment]
I made some major changes to this, if you are interested, check out my commit. Hope this helps. Thanks for your first iteration on this.

Mainly, I introduced a new env DOCKER_BUILD in order to skip validation only during docker build time. This is more accurate than the previous implementation.

**Comment by marcklingen** [comment]
Needed to add `ENV DOCKER_BUILD 0` to the runner in Dockerfile, now it works as expected when testing different combinations locally. lgtm

**Comment by khareyash05** [comment]
> I made some major changes to this, if you are interested, check out my commit. Hope this helps. Thanks for your first iteration on this.
> 
> Mainly, I introduced a new env DOCKER_BUILD in order to skip validation only during docker build time. This is more accurate than the previous implementation.

Yeah looks super optimized!

**Comment by khareyash05** [comment]
> Needed to add `ENV DOCKER_BUILD 0` to the runner in Dockerfile, now it works as expected when testing different combinations locally.

Yeah I did try in out on the locale.

**Pull request merged**
