### PR TITLE
license check for dependencies as GitHub action

### LINKED ISSUE #258: Add license check for dependencies as GitHub action
Goal: make sure only dependencies are added to the project which have a public domain or permissive license, no copyleft. 

Looks like a good starting point: https://github.com/marketplace/actions/dependencies-license-compliance-checker

### PR DESCRIPTION
**Pull request by gokuljs**
## What does this PR do?

Fixes #258

### CODE REVIEW

**Comment by gokuljs** [comment]
#258

**Comment by marcklingen** [comment]
Thanks for the contribution, @gokuljs, looks great! I'd appreciate if you could test this to confirm that it fails if a dependency with a copyleft license is installed

**Comment by gokuljs** [comment]
@marcklingen  currently doing that give 15 min i will get back to you after testing

**Comment by gokuljs** [comment]
@marcklingen works perfectly. I have tested it with a package called 'netgear' (https://www.npmjs.com/package/netgear) which has an MPL 2.0 license. This license falls under the category of weak copyleft licenses. Every time an event occurs, a license checker will examine the 'package.json' file. If it detects any copyleft licenses, it will result in a failure. Please let me know if you would like a video proof. If you do, I will create one and add it here.

**Comment by marcklingen** [comment]
Hi @gokuljs, thanks again, just made a quick attempt to add the failed packages as a comment, but it did not work (that's ok). Rest looks good. Why is https://github.com/yui/yui-lint necessary for the license check to work?

**Comment by gokuljs** [comment]
Hi  @marcklingen,

The inclusion of yui-lint as a dependency is specified in the license-checker npm package documentation because it's necessary for the license check to function properly. You can verify this by checking the license-checker package's documentation here: [license-checker npm package](https://www.npmjs.com/package/license-checker?activeTab=readme).

**Review by marcklingen — APPROVED** [review]

**Comment by marcklingen** [comment]
Thanks for the quick reply, very helpful

**Comment by gokuljs** [comment]
@marcklingen one other is there a easy way to populate data into dashboard when your running langfuse in local ?

**Pull request merged**
