### PR TITLE
Adding deploy with stitch to readme

### PR DESCRIPTION
**Pull request by rdosanjh**
## What does this PR do?

Adds a deploy with Stitch badge to the README.
image

Hey I'm Raj from Stitch (YC W24) and we are building installers for opensource software. After speaking to @clemra we feel like Langfuse could really make use of this.

Here is a short video demo: https://www.loom.com/share/89de0a8a55024c189d99c47bbad36167?sid=68dbb816-fa36-41c4-969c-d71eef472396

The Stitch installer essentially creates infra on the user's cloud and runs a script to install langfuse. We have written the install script using the instructions on the readme. We will be fully opensourcing the Stitch installer so that it is transparent to users exactly what is being run on their cloud.

Please let me know if you have any questions.
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (does not change functionality, e.g. code style improvements, linting)
- [ ] This change requires a documentation update

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Comment by marcklingen** [comment]
Hi @rdosanjh, this is awesome! I'd like to add it to our self-hosting docs: https://langfuse.com/docs/deployment/self-host#platform-specific-information

For us it is very important to know which information is used from the repo to derive the install script and which changes are automatically reflected. Does stitch use the docker compose and match the standard containers (postgres/redis/...) to the fully managed AWS services?

**Comment by rdosanjh** [comment]
Hey @marcklingen thanks for the quick response.

So currently we create an aws ec2 instance and run the following script in userdata:

```
#!/bin/bash
#testesttse

sudo yum install docker -y

# install docker-compose
sudo curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose

sudo systemctl start docker

sudo yum install git -y

# Clone repository
git clone https://github.com/langfuse/langfuse.git
cd langfuse

# Run server and database
sudo docker-compose up -d
```

We are aware that this isn't a production level install and are super happy to work on the way we do the deployment if needed.

We are also actively developing a way to get telemetry from installs and remotely push updates. Here are some screenshots

image

image

**Comment by marcklingen** [comment]
Thanks a lot for the quick response.

This is a great way to get started similar to the Railway deployment but I assumed it would use a separate postgres db as we currently discourage users from using docker compose in prod (this might change as infrastructure gets more complex).

Do you have more user-facing docs or explanations that we could add/link? probably interesting for most who'd want to try this: instance size configuration, health monitoring, how do upgrades work

**Comment by marcklingen** [comment]
I can either write this or you can also add it to https://github.com/langfuse/langfuse-docs/blob/main/pages/docs/deployment/self-host.mdx

**Comment by rdosanjh** [comment]
Thanks for taking a look @marcklingen . I've made a PR to the docs page here https://github.com/langfuse/langfuse-docs/pull/359

**Comment by marcklingen** [comment]
thx @rdosanjh, merged. The installer looks great by the way

**Pull request closed without merging**
