### PR TITLE
feat(auth): add GitHub Enterprise Authentication Provider

### PR DESCRIPTION
**Pull request by jay0129**
## What does this PR do?
This PR introduces a new authentication provider for GitHub Enterprise, allowing users to configure their SSO (Single Sign-On) through GitHub Enterprise instances, similar to existing GitHub, GitLab, and other provider configurations.

## Discussion
https://github.com/orgs/langfuse/discussions/4413

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Mandatory Tasks
- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist
- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

----

> [!IMPORTANT]
> Adds GitHub Enterprise as a new authentication provider, updating environment variables, schemas, and UI components to support it.
> 
>   - **Behavior**:
>     - Adds `GitHubEnterpriseProvider` in `gitHubEnterpriseProvider.ts` to support GitHub Enterprise authentication.
>     - Updates `auth.ts` to include GitHub Enterprise in static providers if environment variables are set.
>     - Modifies `sign-in.tsx` to include a button for GitHub Enterprise login.
>   - **Environment Variables**:
>     - Adds `AUTH_GITHUB_ENTERPRISE_CLIENT_ID`, `AUTH_GITHUB_ENTERPRISE_CLIENT_SECRET`, `AUTH_GITHUB_ENTERPRISE_BASE_URL`, and `AUTH_GITHUB_ENTERPRISE_ALLOW_ACCOUNT_LINKING` to `.env.prod.example` and `env.mjs`.
>   - **Schemas**:
>     - Adds `GithubEnterpriseProviderSchema` in `types.ts` to define the schema for GitHub Enterprise authentication configuration.
>   - **Exports**:
>     - Exports `GitHubEnterpriseProvider` in `index.ts` for use in other modules.
>   - **Utilities**:
>     - Updates `utils.ts` to handle GitHub Enterprise in `dbToNextAuthProvider()` function.
> 
> <sup>This description was created by </sup>[Ellipsis](https://www.ellipsis.dev?ref=langfuse%2Flangfuse&utm_source=github&utm_medium=referral)<sup> for c041e9f3bb1339b047d7c397422979d366da7589. It will automatically update as commits are pushed.</sup>

### CODE REVIEW

**Comment by marcklingen** [comment]
Thanks for opening his PR.Have you tried using this end-to-end with your internal GHE provider?

**Comment by jay0129** [comment]
> Thanks for opening his PR. Have you tried using this end-to-end with your internal GHE provider?

Yes. I logged in successfully with my GHE authentication app and finally saw the greetings page.

**Comment by marcklingen** [comment]
awesome, thanks for confirming!

**Review by marcklingen — APPROVED** [review]
This looks great! Thank you for your contribution and self-review. It will be included in the next v3 release.

**Comment by marcklingen** [comment]
Just brought this to v2 as well in case it is relevant for you, published container will be available in an hour

https://github.com/langfuse/langfuse/releases/tag/v2.93.3

**Pull request merged**
