### PR TITLE
feat(ui): improve trace view: collapse/expand observation tree + color coding of observation types

### LINKED ISSUE #451: feat: Improve observation tree UI
### Describe the feature you'd like to request

there is no color to help customer identify if the trace is good or not.

### Describe the solution you'd like to see

Especially for some error traces, it is better to use red to highlight that.

### Additional information

_No response_

### Contribute

- [ ] Yes, I can implement this and raise a PR

### PR DESCRIPTION
**Pull request by functorism**
## What does this PR do?

This PR initiates a suggestion for some changes to the Trace view that I consider to improve the readability of traces. These suggested changes include:

* Color coding of Observation Type
* Ability to collapse child traces
* Ability to collapse and expand all traces
* Makes the trace view a little bit wider
* Make the padding a little bit smaller, to retrieve some more space for viewing traces

At this point I just want to have a conversation and get some feedback to see if changes in this line is desired by the maintainers.

Going forward I would be open to making more significant changes:

* Adding fuzzy search to make it easier to find deeply nested traces by run-name
* Being able to focus on a sub-trace-tree, allowing to render that sub-tree with the full space of the container
* Seek to send more useful data from the langchain integration to provide richer information in the trace view, especially better handling of run-names

2024-01-20-18-20-02-scrot

## Type of change

- [x] Chore (refactoring code, technical debt, workflow improvements)
- [x] New feature (non-breaking change which adds functionality)

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my PR needs changes to the documentation

### CODE REVIEW

**Comment by davidfant** [comment]
This looks banger! 🔥

**Comment by b-yukky** [comment]
Looks awesome!! Looking forward to it

**Comment by marcklingen** [comment]
This is great @functorism and something I wanted to get to for a long time already.

> Color coding of Observation Type

Looks great, we will do a color overhaul at one point but it is not a priority yet. Until then, let's stick with the colors you suggested.

> Makes the trace view a little bit wider
Make the padding a little bit smaller, to retrieve some more space for viewing traces

👍 (great to view more observations)

> Ability to collapse child traces
Ability to collapse and expand all traces

Love it, minor changes that I'd suggest. What do you think?

- [ ] Replace Toggles with Buttons for expandAll and collapseAll, since Toggles don't have a pressed state.
- [ ] Add a pressed state to the expand/collapse toggles of each node.
- [ ] Prevent propagation on the toggles/buttons to avoid altering the active observation.
- [ ] Icons: Use [+] and [-] icons to expand/collapse individual nodes instead of chevrons. Maybe there are also [++] and [--] icons for expandAll and collapseAll to make this more clear and distinct from the chevrons on the existing toggle

Let's get this merged and then discuss the other ideas in https://github.com/langfuse/langfuse/discussions

**Comment by functorism** [comment]
Agree with all the revisions you suggest, I'll fix that and update the PR. Thanks for the feedback!

**Comment by marcklingen** [comment]
> Agree with all the revisions you suggest, I'll fix that and update the PR. Thanks for the feedback!

Awesome, looking forward to it! Let me know if I can help

**Comment by functorism** [comment]
2024-02-10-20-30-03-scrot

You comments should all have been addressed in the latest commit @marcklingen

**Review by marcklingen — APPROVED** [review]
This is awesome, thanks a lot! This is a major UI improvement. Let's discuss your other ideas here: https://github.com/langfuse/langfuse/discussions

**Pull request merged**
