### PR TITLE
feat: add custom webhook functionality

### PR DESCRIPTION
**Pull request by khareyash05**
## What does this PR do?
Adds custom webhook functionality for prompt/score/dataset creation

Fixes #1033 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (does not change functionality, e.g. code style improvements, linting)
- [ ] This change requires a documentation update

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Comment by khareyash05** [comment]
Added a v1 where people can actually plugin their Custom Webhook Urls and process the data.

However the data sent can be more presentable as of now its if sending all of the data it received via prompt/score creation

**Comment by marcklingen** [comment]
Hi @khareyash05, please checkout our contributing.md. I cannot review this PR as it is not a priority right now. Check out the list of open issues if you'd like to contribute to the project. The ideas on github discussions reflect more of a potential roadmap than things that should be implemented asap. Most of them need way more details and spec before getting started with the development as otherwise this project would become a mess to maintain.

**Comment by khareyash05** [comment]
> Hi @khareyash05, please checkout our contributing.md. I cannot review this PR as it is not a priority right now. Check out the list of open issues if you'd like to contribute to the project. The ideas on github discussions reflect more of a potential roadmap than things that should be implemented asap. Most of them need way more details and spec before getting started with the development as otherwise this project would become a mess to maintain.

Understood. Thanks a lot. I will keep that in mind.

**Comment by marcklingen** [comment]
Thanks a lot for your contribution to Langfuse 🙏

**Pull request closed without merging**
