### PR TITLE
feat(ui): preview of OpenAI function calls

### PR DESCRIPTION
**Pull request by georgegebbett**
## What does this PR do?

Currently if you are using the OpenAI Function Calling API, pretty viewing of Generation input is disabled unless you send only your messages array to Langfuse as the input. This causes the token count to be incorrect, because the tokens used to contain the function definitions aren't included in the information sent to Langfuse.

If you send the complete object consisting of the messages and functions arrays to Langfuse, the token count is correct, but you are not able to view the input in the OpenAI pretty view:
image

This PR allows messages with role `function` to be visualised in the pretty view:

image
 
You can still go back to the JSON view to see the full input, including the function definitions. 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (does not change functionality, e.g. code style improvements, linting)
- [ ] This change requires a documentation update

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by marcklingen** [comment]
This looks great, ty! I'll try to review and merge / give feedback soon

**Comment by marcklingen** [comment]
Thanks again!

**Review by marcklingen — APPROVED** [review]

**Comment by ushuz** [comment]
Just a note, based on OpenAI docs (https://platform.openai.com/docs/api-reference/chat), `functions` and `function_call` are deprecated in favour of `tools` and `tool_choice`.

**Comment by marcklingen** [comment]
thanks for sharing, will update the UI soon to reflect this @ushuz!

**Comment by marcklingen** [comment]
Improvement to this just merged in this PR: https://github.com/langfuse/langfuse/pull/1388

**Pull request merged**
