### PR TITLE
fix: username and logo goes down as no. of projects increases

### LINKED ISSUE #758: bug: User Name and Logo goes down as No. of Projects increase
### Describe the bug

As no. of projects increase, the user logo as well as name goes down the sidebar. This is visually less appealing. We can shift the logo to the top-right . It will be more appealing .

### To reproduce

Increase the number of projects and see the logo goes down

### Additional information

Screenshot from 2023-12-24 10-03-56
Screenshot from 2023-12-24 10-03-50

### PR DESCRIPTION
**Pull request by TameemAsim**
## What does this PR do?

fixed: username and logo goes down as no. of projects increases

Fixes #758 

 Loom Video: https://www.loom.com/share/eb4ebe5718824e37889c17b0fe6423b1?sid=283431a2-b454-4012-9d63-1066095fee97

## Type of change

- [ x ] Bug fix (non-breaking change which fixes an issue)

## Mandatory Tasks

- [ x ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Comment by khareyash05** [comment]
Looks great!

**Comment by 18feb06** [comment]
Thanks

**Comment by khareyash05** [comment]
Maybe we can permanently shift the logo to the top. What do you say @marcklingen ?

**Comment by maxdeichmann** [comment]
@18feb06 thanks a lot for the contribution. I think this is a great change. I will merge this and deploy it with the next release.

**Comment by maxdeichmann** [comment]
> Maybe we can permanently shift the logo to the top. What do you say @marcklingen ?

What exactly do you mean? Currently, the logo is fixed at the top.

**Comment by khareyash05** [comment]
> > Maybe we can permanently shift the logo to the top. What do you say @marcklingen ?
> 
> What exactly do you mean? Currently, the logo is fixed at the top.

For all screen sizes, maybe we can move it to the top right ?

**Comment by 18feb06** [comment]
@maxdeichmann Thanks for Merging

**Pull request merged**
