### PR TITLE
feat(auth): Add access to default project upon sign-up

### PR DESCRIPTION
**Pull request by ushuz**
## What does this PR do?

This is to add two environment variables:
- `LANGFUSE_DEFAULT_PROJECT_ID`
- `LANGFUSE_DEFAULT_PROJECT_ROLE`

Once set, new users will be automatically added to the default project with the preset role upon sign-up.

This is good for self-hosted Langfuse instance for a team.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (does not change functionality, e.g. code style improvements, linting)
- [ ] This change requires a documentation update

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by marcklingen** [comment]
Hi @ushuz, this is super useful. In fact this functionality partly already exists with `NEXT_PUBLIC_DEMO_PROJECT_ID` (used for the public demo on langfuse cloud). Can we merge `LANGFUSE_DEFAULT_PROJECT_ID` and `NEXT_PUBLIC_DEMO_PROJECT_ID`?

**Comment by ushuz** [comment]
@marcklingen Thanks. This is inspired by how the demo project adds access for new sign-ups. 

However, `NEXT_PUBLIC_DEMO_PROJECT_ID` is referenced in multiple templates to render elements that are specific to Langfuse Cloud, while `LANGFUSE_DEFAULT_PROJECT_ID` is mostly for self-hosted, I'm not sure what's the best way to merge them.

**Comment by marcklingen** [comment]
@ushuz, agree, let's keep them separate. I moved the logic to a new function `createProjectMembershipsOnSignup` to apply it both to SSO and email/password users. Happy to get this merged when you confirm the cla

**Comment by marcklingen** [comment]
@ushuz released in https://github.com/langfuse/langfuse/releases/tag/v1.11.0 in case you want to pull the production container

**Pull request merged**
