### PR TITLE
feat: well designed email template for project invitation to non-account users

### LINKED ISSUE #600: feat: Well-Designed Email Template for Project Invitations
### Describe the feature you'd like to request

Well-Designed Email Template for Project Invitations with with right color scheme.

### Describe the solution you'd like to see

Well-Designed Email Template for Project Invitations with with right color scheme.

### Additional information

_No response_

### Contribute

- [X] Yes, I can implement this and raise a PR

### PR DESCRIPTION
**Pull request by TameemAsim**
## What does this PR do?

added an email template for project invitation using [React Email](https://react.email/) library.

Fixes #600 

 Loom Video: https://www.loom.com/share/9df956e153e74e55bc883ff8ddcb96bc?sid=b6a66afb-ac60-4cee-bf32-d1c2b1703420

## Type of change

- [ x ] New feature (non-breaking change which adds functionality)

## Mandatory Tasks

- [ x ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Comment by 18feb06** [comment]
Open to any change or discussion.

**Comment by marcklingen** [comment]
This looks awesome, @18feb06! Will check this out tomorrow and get it merged

**Comment by 18feb06** [comment]
Thanks

**Review by marcklingen — APPROVED** [review]

**Comment by marcklingen** [comment]
Thanks @18feb06, this looks awesome
CleanShot 2023-12-01 at 02 16 04@2x

**Pull request merged**
