### PR TITLE
Add magic-link auth

### PR DESCRIPTION
**Pull request by marcklingen**
Add magic-link auth using smtp connection

### CODE REVIEW

**Comment by marcklingen** [comment]
Moved Google & GitHub auth to separate PR: #405

**Comment by marcklingen** [comment]
@p5 @yusukegoto, I see that you upvoted on this PR. Are you interested in magic-link auth? As I see most users either preferring SSO or email/password (in password manager) for tools they use frequently, I'd otherwise close this issue

**Comment by p5** [comment]
> @p5 @yusukegoto, I see that you upvoted on this PR. Are you interested in magic-link auth? As I see most users either preferring SSO or email/password (in password manager) for tools they use frequently, I'd otherwise close this issue

We're using SSO and it's been working great, so magic link isn't necessary for us.  Happy for this th be closed.
Just thought it was a cool feature that I wanted to follow

**Comment by marcklingen** [comment]
Thanks for confirming @p5, any SSO options missing for your team?

**Comment by p5** [comment]
> Thanks for confirming @p5, any SSO options missing for your team?

@marcklingen Nope.  Google SSO was the main one, and it's working great

**Comment by marcklingen** [comment]
Glad to hear that.

If anyone really wants this, let us know. Closing this for now

**Pull request closed without merging**
