### PR TITLE
feat(ui): display host name on project settings page

### LINKED ISSUE #712: feat(ui): Show hostname on settings
### Describe the feature you'd like to request

While watching a friend set up Langfuse, they wondered what region they signed up in (as they weren't sure anymore).

Instinctively, they looked in the settings section. (i then pointed that it'd probably also be shown in the url - but showing it more visually wouldn't hurt)

### Describe the solution you'd like to see

In the user settings, display the region / baseUrl you are in.

### Additional information

_No response_

### Contribute

- [ ] Yes, I can implement this and raise a PR

### PR DESCRIPTION
**Pull request by khareyash05**
## What does this PR do?

Added hostname/base url on settings page
Fixes #712 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (does not change functionality, e.g. code style improvements, linting)
- [ ] This change requires a documentation update

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Comment by marcklingen** [comment]
Thanks for your contribution @khareyash05, I've just made a small change to the component to simplify it, lgtm!

**Review by marcklingen — APPROVED** [review]

**Comment by khareyash05** [comment]
Thank you @marcklingen . Looking forward to contributing more and more.

**Comment by marcklingen** [comment]
aaand it's released: https://github.com/langfuse/langfuse/releases/tag/v1.23.0
thx @khareyash05

**Comment by khareyash05** [comment]
Looks awesome!!

**Pull request merged**
