### PR TITLE
feat(auth): add Okta

### PR DESCRIPTION
**Pull request by marcklingen**

### CODE REVIEW

**Comment by marcklingen** [comment]
@lucasiscovici
```
docker pull ghcr.io/langfuse/langfuse:2.14.6-0
```

**Comment by qlimenoque** [comment]
I've tested Okta SSO integration and it works as expected
```
AUTH_OKTA_CLIENT_ID=<CLIENT_ID>
AUTH_OKTA_CLIENT_SECRET=<CLIENT_SECRET>
AUTH_OKTA_ISSUER=https://<ORGANIZATION>.okta.com/
AUTH_OKTA_ALLOW_ACCOUNT_LINKING=false
```

I used the next parameters in **Okta Application**:

**Sign-in redirect URIs:**
```
https://<HOST>/api/auth/callback/okta
```
**Sign-out redirect URIs** 
```
https://<HOST>/
```
**OpenID Connect ID Token**
```
Issuer - Okta URL (https://<ORGANIZATION>.okta.com)
```

**Comment by marcklingen** [comment]
thanks for testing/confirming @qlimenoque, will merge soon

**Comment by marcklingen** [comment]
available as of https://github.com/langfuse/langfuse/releases/tag/v2.15.2

**Comment by qlimenoque** [comment]
@marcklingen it would be great to leave a note somewhere about `/api/auth/callback/okta` path. It wasn't obvious at first time

**Comment by marcklingen** [comment]
Agree, I just updated the docs to make this more clear: https://github.com/langfuse/langfuse-docs/commit/e9f4f2a5c485138f401658b759a1e09307fa3ea8

**Comment by tmwatchanan** [comment]
I just tried in my self-hosted Langfuse. But I encountered this error. Any idea how to solve it? I can still use email/pwd authentication without any issue. I've set the following:
- `AUTH_OKTA_CLIENT_ID`
- `AUTH_OKTA_CLIENT_SECRET`
- `AUTH_OKTA_ISSUER`
- `NEXTAUTH_SECRET`
- `NEXTAUTH_URL` is my domain https://<my-domain>.com

```
[next-auth][error][SIGNIN_OAUTH_ERROR] 
https://next-auth.js.org/errors#signin_oauth_error read ECONNRESET {
  error: {
    message: 'read ECONNRESET',
    stack: 'Error: read ECONNRESET\n' +
      '    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)',
    name: 'Error'
  },
  providerId: 'okta',
  message: 'read ECONNRESET'
}
```

**Pull request merged**
