### PR TITLE
feat(ui): keep logo static on large screens while scrolling the main menu

### PR DESCRIPTION
**Pull request by gokuljs**
## What does this PR do?

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (does not change functionality, e.g. code style improvements, linting)
- [ ] This change requires a documentation update

## Mandatory Tasks

- [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project (`npm run prettier`)
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my PR needs changes to the documentation
- I haven't checked if my changes generate no new warnings (`npm run lint`)
- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by gokuljs** [comment]
Uploading Screen Recording 2023-11-25 at 8.15.57 AM.mov…

**Comment by gokuljs** [comment]
https://github.com/langfuse/langfuse/assets/51263906/3a137f48-b2a4-45ed-81a0-3444e6f4618f

**Comment by gokuljs** [comment]
#503

**Comment by gokuljs** [comment]
@

**Comment by marcklingen** [comment]
Hi @gokuljs, thank you for your contribution. I believe it's a great idea to keep the logo fixed on the desktop. I removed the custom CSS for the scrollbar since the default scrollbar on each platform should work perfectly fine. Happy to get this merged, can you accept the [cla](https://cla-assistant.io/langfuse/langfuse?pullRequest=571)?

**Review by marcklingen — APPROVED** [review]

**Comment by gokuljs** [comment]
will do

**Pull request merged**
