### PR TITLE
chore: add K8s deployments

### LINKED ISSUE #236: [LFC-203] Kubernetes deployments
We should have a simple Kubernetes setup to get running fast. We would need:

* [ ] Kubernetes deployment
* [ ] Kubernetes service
* [ ] Secret configs
* [ ] DB config via env variables

Optional: docs, can be follow-up issue

<sub>From [SyncLinear.com](https://synclinear.com) | [LFC-203](https://linear.app/langfuse/issue/LFC-203/kubernetes-deployments)</sub>

### PR DESCRIPTION
**Pull request by khareyash05**
## What does this PR do?

Adds langfuse-deployment and service with  secrets
Fixes #236 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Chore (refactoring code, technical debt, workflow improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (does not change functionality, e.g. code style improvements, linting)
- [ ] This change requires a documentation update

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Comment by marcklingen** [comment]
Thanks for your contribution, let me know when this is ready to review @khareyash05

**Comment by khareyash05** [comment]
Hi @marcklingen , A few questions on my mind right now. I am sorry these questions might be basic I have recently started on K8s
1. DB_URL, NEXTAUTH_URL,NEXTAUTH_SECRET, SALT are the only Secrets required right?
2. K8s setup is for Production right?
3. How can I get hold of Secrets?Should I use the env.dev.example? As Production Secrets required db id and password?,

**Comment by khareyash05** [comment]
@marcklingen Ready for review

**Comment by khareyash05** [comment]
@marcklingen @maxdeichmann Ready for review!

**Comment by marcklingen** [comment]
Perfect @khareyash05, just asked a team who runs Langfuse on K8S in prod to review the PR

**Comment by marcklingen** [comment]
Can you add a k8s test to the change which basically runs the k8s config and runs the server tests to check whether it works as expected?

**Comment by khareyash05** [comment]
> Can you add a k8s test to the change which basically runs the k8s config and runs the server tests to check whether it works as expected?

A script to test whether the cluster is working perfectly or not. Right?

**Comment by marcklingen** [comment]
Allright @khareyash05, do you want to make any other changes? Just got the confirmation that this looks great and am happy to merge as a community maintained K8s deployment option. I'll also reference it in the docs then.

**Comment by khareyash05** [comment]
> Allright @khareyash05, do you want to make any other changes? Just got the confirmation that this looks great and am happy to merge as a community maintained K8s deployment option. I'll also reference it in the docs then.

Done! @marcklingen. Can I help mentioning in the docs?

**Comment by marcklingen** [comment]
Hi @khareyash05 this is still awesome, would love to add this asap. I've just created a separate repo to host this community-maintained k8s config. Happy to move this change to the new repo unless you want to raise the PR yourself.

**Comment by khareyash05** [comment]
Thank you for giving the opportunity. Would love to add this!. Shall I just move all the files as they are in the k8s repo? Thanks again

**Comment by marcklingen** [comment]
That’d be great

**Comment by khareyash05** [comment]
> That’d be great

Done [https://github.com/langfuse/langfuse-k8s/pull/1](https://github.com/langfuse/langfuse-k8s/pull/1) Have a look

**Comment by marcklingen** [comment]
Merged, thank you!

**Pull request closed without merging**
