### PR TITLE
feat(auth): add Okta

### LINKED ISSUE #507: feat: Add Okta
### Describe the feature you'd like to request

Our company uses Okta and next.js includes an okta provider, so this request is to add Okta as an auth provider

### Describe the solution you'd like to see

A signin with Okta button

### Additional information

Here's the PR: https://github.com/langfuse/langfuse/pull/506 

### Contribute

- [X] Yes, I can implement this and raise a PR

### PR DESCRIPTION
**Pull request by chaseWillden**
Add Okta as a provider for enterprise type of users

### CODE REVIEW

**Comment by marcklingen** [comment]
@chaseWillden thanks for adding this. I don't have a production/sandbox Okta. Can you confirm that this works as expected on your end? Happy to get this merged

**Review by marcklingen — APPROVED** [review]

**Comment by chaseWillden** [comment]
> @chaseWillden thanks for adding this. I don't have a production/sandbox Okta account. Can you confirm that this works as expected on your end? Happy to get this merged

Sorry for the slow reply, I'm trying to work with my company to allow us to use our okta instance to verify this

**Comment by marcklingen** [comment]
No worries, thanks for the update

**Comment by marcklingen** [comment]
@chaseWillden any update on this? There shouldn't be any leakage of data if you test it locally but I understand if that's not enough from an internal security perspective.

**Comment by mritonia** [comment]
Any status on this PR?

**Comment by marcklingen** [comment]
happy to add this if we can try it in your okta environment @mritonia. I can create a pre-release version which you can deploy to confirm that it works as expected. let me know if you are interested

**Comment by lucasiscovici** [comment]
Any update ?

**Comment by marcklingen** [comment]
@lucasiscovici I can create a new pre-release container which includes the okta provider, are you open to test it? I do not want to merge it before knowing that this works reliably

**Comment by marcklingen** [comment]
testing = pulling the pre-release version and verifying that this works as expected when setting the env variables for Okta. This should be super easy if you use Okta in your organization

**Comment by lucasiscovici** [comment]
ok come on ! :)

**Comment by marcklingen** [comment]
perfect, merging into branch to create a pre-release container

**Comment by marcklingen** [comment]
available as of https://github.com/langfuse/langfuse/releases/tag/v2.15.2

**Pull request merged**
