### PR TITLE
feat(api): add `lastConfig` attribute and `fromUpdatedAt` and `toUpdatedAt` query params to `GET /v2/prompts`

### PR DESCRIPTION
**Pull request by marcklingen**
based on discussion: #2684

### CODE REVIEW

**Comment by marcklingen** [comment]
ready to be merged, waiting for feedback by @ashutoshsaboo in discussion thread

**Comment by ashutoshsaboo** [comment]
Hey Marc, I'll get back on the PR by tomorrow.

**Comment by marcklingen** [comment]
Thanks

**Comment by ashutoshsaboo** [comment]
@marcklingen since we are returning lastConfig for even non-filter cases, we should probably also return for which version of the prompt was the config returned, else it can get confusing for the client to figure out the same. It might be a good idea to also return the same for the filter cases, i.e, show matching version number for which query filters were passed and config was returned.

**Comment by marcklingen** [comment]
Thanks for the feedback, I think the current output is good enough as "last" refers to max(versions[]). thanks for your additional feedback in the discussion thread. will add the time-based filters as well as you suggested

**Comment by ashutoshsaboo** [comment]
this is great, thanks Marc! @marcklingen

**Pull request merged**
