### PR TITLE
Successfully redirected to initial URL after sign-in.

### LINKED ISSUE #1093: feat(auth): post-login redirect to initial url
Deeplinks to traces are a popular feature. Currently if a user is unauthenticated, the deep link does not work as expected as it is not persisted when redirecting an unauthed user to the login page (see layout.tsx).

Steps

- [ ] Add target url to auth page as url param in redirect (layout.tsx)
- [ ] Persist target url while signing in (managed by AuthJS/NextAuth)
- [ ] Add e2e test for this behavior (playwright)

### PR DESCRIPTION
**Pull request by Dharshan-K**
Fixes #1093 

feat(auth): post-login redirect to initial url. Your feedback is greatly appreciated.

### CODE REVIEW

**Comment by Dharshan-K** [comment]
Hi, Is there any error or mistake in my PR.

**Comment by marcklingen** [comment]
Hi @Dharshan-K, appreciate your contribution on this!

Please have a look at the original issue:

- [ ]  Add target url to auth page as **url param** in redirect (layout.tsx) - **currently in state and not a URL param**
- [X]  Persist target url while signing in (managed by AuthJS/NextAuth)
- [ ]  Add e2e test for this behavior (playwright) - **tests failing**

Let me know if you have any questions

**Comment by marcklingen** [comment]
@Dharshan-K do you plan to update this PR or shall I close this?

**Comment by marcklingen** [comment]
closing in favor of https://github.com/langfuse/langfuse/pull/1913

**Pull request closed without merging**
