### PR TITLE
fix: add Gitlab Issuer and Account.created_at col

### PR DESCRIPTION
**Pull request by vanshavenger**
## What does this PR do?

According to Feat: Add Gitlap Provider PR, It was suggested to add the GITLAB ISSUER to the secrets - #3564 

But Please make sure the instance is self hosted.
Tho According to the docs it was not needed. Just an FYI

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)

## Mandatory Tasks

- [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

cc @marcklingen 

----

> [!IMPORTANT]
> Add `AUTH_GITLAB_ISSUER` configuration for GitLab authentication provider.
> 
>   - **Environment Configuration**:
>     - Add `AUTH_GITLAB_ISSUER` to `.env.prod.example` and `env.mjs` as an optional string.
>   - **Authentication Setup**:
>     - Update `auth.ts` to include `issuer: env.AUTH_GITLAB_ISSUER` in `GitLabProvider` configuration.
> 
> <sup>This description was created by </sup>[Ellipsis](https://www.ellipsis.dev?ref=langfuse%2Flangfuse&utm_source=github&utm_medium=referral)<sup> for 39d249379f9e9f4f04e52689f31c4978f76a1791. It will automatically update as commits are pushed.</sup>

### CODE REVIEW

**Review by marcklingen — APPROVED** [review]
looks good!
- added missing col to schema
- added issuer to multi-tenant sso config

**Comment by marcklingen** [comment]
by the way, I'd recommend to test these kinds of prs before creating a PR to make sure that they actually work. Without the column that I just added this most likely never worked even for those who do not need a custom issuer configuratio

**Comment by ptempier** [comment]
> by the way, I'd recommend to test these kinds of prs before creating a PR to make sure that they actually work. Without the column that I just added this most likely never worked even for those who do not need a custom issuer configuratio

I think it actually worked, but only if your gitlab instance was https://gitlab.com/ ; ie if you worked at gitlab.
Cause i was still redirected to an auth page. Hence why i was trying to explain that gitlab is not github. While there are many instances of gitlab, github is more like one public instance of github with a well known url.

**Comment by ptempier** [comment]
You think i could get that packaged in a docker to test today ?
Or i can just git clone the repo and that would be my container with no need to compile anything ?
Or should i wait for the next release ?

**Comment by marcklingen** [comment]
Interesting, this did not work for me when using gitlab.com as the created_at col was missing in the database (as mentioned in the [nextauth docs](https://next-auth.js.org/providers/gitlab))

**Comment by marcklingen** [comment]
> You think i could get that packaged in a docker to test today ? Or i can just git clone the repo and that would be my container with no need to compile anything ? Or should i wait for the next release ?

Yes, just pull the image from main branch: langfuse/langfuse:main

We will include it in the next release, let me know in case this does not work

**Comment by ptempier** [comment]
Same thing, i get redirected to https://gitlab.com/users/sign_in
I did try with wiping the db and open in incognito mode.
i have set :

- DATABASE_URL=postgresql://xxx:xxx@langfuse-db:5432/langfuse
- NEXTAUTH_SECRET=xxx # openssl rand -base64 32
- SALT=xxx # openssl rand -base64 32
- ENCRYPTION_KEY=xxx # generate via `openssl rand -hex 32`
- NEXTAUTH_URL=https://langfuse.mycompagny.com
- TELEMETRY_ENABLED=false
- LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES=false
- AUTH_GITLAB_CLIENT_ID=xxx
- AUTH_GITLAB_CLIENT_SECRET=xxx
- AUTH_GITLAB_ALLOW_ACCOUNT_LINKING=true
- AUTH_GITLAB_ISSUER=https://gitlab.mycompagny.com
- AUTH_DOMAINS_WITH_SSO_ENFORCEMENT=mycompagny.com

**Comment by vanshavenger** [comment]
https://github.com/phasehq/console/pull/259/files

Check this once, will dig more through it on friday as currently don’t have
my personal laptop with me.

According to next auth docs it was not mentioned anywhere.

But ig this issue will help us understand more about self hosted instance

**Comment by marcklingen** [comment]
> Same thing, i get redirected to https://gitlab.com/users/sign_in I did try with wiping the db and open in incognito mode. i have set :
> 
> * DATABASE_URL=postgresql://xxx:xxx@langfuse-db:5432/langfuse
> * NEXTAUTH_SECRET=xxx # openssl rand -base64 32
> * SALT=xxx # openssl rand -base64 32
> * ENCRYPTION_KEY=xxx # generate via `openssl rand -hex 32`
> * NEXTAUTH_URL=https://langfuse.mycompagny.com
> * TELEMETRY_ENABLED=false
> * LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES=false
> * AUTH_GITLAB_CLIENT_ID=xxx
> * AUTH_GITLAB_CLIENT_SECRET=xxx
> * AUTH_GITLAB_ALLOW_ACCOUNT_LINKING=true
> * AUTH_GITLAB_ISSUER=https://gitlab.mycompagny.com
> * AUTH_DOMAINS_WITH_SSO_ENFORCEMENT=mycompagny.com

Interesting as this is passed here: https://github.com/langfuse/langfuse/blob/674bdbd9768d1d34f99a882a03ffe2ddf0dc8823/web/src/server/auth.ts#L237

Open for any contributions to this as I cannot replicate the issue

**Pull request merged**
